<?php

$data = [
    "[2018-03-13 12:16:10] test.DEBUG: Test message [",
    "[2018-03-13 12:16:10] test.ERROR: Test message [",
    "[2018-03-13 12:16:10] test.WARNING: Test message [",
    "[2018-03-13 12:16:10] test.WARNING: Test message [",
    "[2018-03-13 12:16:10] test.INFO: Test message [",
    "[2018-03-13 12:16:10] test.NOTICE: Test message [",
    "[2018-03-13 12:16:10] test.EMERGENCY: Test message [",
    "[2018-03-13 12:16:10] test.ALERT: Test message [",
    "[2018-03-13 12:16:10] test.ERROR: Test message [",
    "[2018-03-13 12:16:10] test.NOTICE: Test message ["
];

$words = [
    'a*a11yabendabsolute',
'pathabstract',
'classabstract',
'data',
'typeabstractionacceptance',
'testingaccessibilityacmeactionscriptaddress',
'resolution',
'protocol',
'(arp)address',
'space',
'layout',
'randomizationadgerafaictagileahkajaxalgebraic',
'data',
'typealgorithmallocationalphaamd64analogandroidangularjsanonymous',
'functionansibleanti-patternapache',
'luceneapache',
'pigapache',
'solrapi',
'(application',
'programming',
'interface)appcacheappkitar',
'(augmented',
'reality)architectureargumentsariaarityarrayarray',
'indexarray',
'listarrow',
'functionsasicassemblerassembly',
'languageassignment',
'statementassistive',
'technologyassociative',
'array',
'(php)ast',
'(abstract',
'syntax',
'tree)asynchronousatomatomic',
'operationauthenticationauthorizationauto',
'idawkawsaxiosazure',
'ba',
'(business',
'analyst)babelback-endbacklogbackronymbackupbag',
'of',
'wordsbangbarbar',
'codebarbbashbasicbatchbazbc',
'(backwards',
'compatibility)bc',
'(business',
'continuity)best',
'practicebetabi',
'(business',
'intelligence)big',
'bangbig',
'databig',
'obig-endianbikesheddingbinarybinary',
'operatorbinary',
'search',
'treebinary',
'treebitbit',
'bangbit',
'rotbitbucketbitcoinbitmaskbitwise',
'operatorsblack',
'hat',
'hackerblenderblob',
'(binary',
'large',
'object)blockchainbodgebogonbogosortboilerplate',
'codebooleanbootstrapborkedbotbotnetbouncebowerboxboxenboyscoutingbrackets',
'(text',
'editor)brainfuckbranch',
'and',
'boundbrogrammerbrowserbrute',
'forcebsodbufferbugbuildbuild',
'or',
'buybuild',
'outbuild',
'upbuilderbundlerbytebytecode',
'(language)c#c++cachecall',
'stackcallbackcallback',
'hellcalling',
'a',
'functioncamel',
'casecanvas',
'(html)captchacargo',
'cultingcarthagecassandracastcategorycategory',
'theorycdn',
'(content',
'delivery',
'network)celerychange',
'control',
'managementchangelogcheckoutchromechronicle',
'queuecicircleciciscclangclasscliclientclient-server',
'modelclobberclojureclone',
'and',
'goclosed',
'sourceclosed-form',
'expressionclosurecloudcmdcms',
'(content',
'management',
'system)cnd',
'(content',
'delivery',
'network)cobolcochcarnacocoacodecode',
'bloatcode',
'debtcode',
'monkeycode',
'reviewcode',
'rotcode',
'smellcodeignitercodingcoffeecoffeescriptcohesioncold',
'sitecolorzillacommandcommand',
'patterncommit',
'(git)comparison',
'operatorscompiled',
'languagecompilercomponentcomposer',
'(php)compressioncomputer',
'appliancecomputer',
'languageconcurrencyconditional',
'executionconditionalsconfluenceconnascenceconsoleconstantconstant',
'timeconstructorcontinuous',
'deliverycontinuous',
'deploymentcontinuous',
'integrationcontravariancecontravariant',
'functorconvention',
'over',
'configurationconways',
'lawcookiecoqcore',
'datacore',
'memorycoroutinecouplingcovariancecpqcqrscqscreate-react-appcroncron',
'jobcross-platformcrud',
'(create,',
'read,',
'update,',
'delete)cruftcrystalcsscss',
'frameworkctfcurryingcursorcvecyclomatic',
'complexityc艹',
'daemondagdance',
'of',
'deathdartdata',
'classdata',
'dictionarydata',
'racedata',
'sciencedata',
'storedata',
'structuredata',
'transfer',
'objectdatabasedatabase',
'indexdddddosdeadlockdebuggerdebuggingdecimaldeclarationdeclarative',
'programmingdecompilationdecompositiondecouplingdefense',
'in',
'depthdeferreddelegatedelegationdelphideltadenormalizedependencydependency',
'helldependency',
'injectiondependency',
'managementdeploydeprecateddereferencedereference',
'a',
'null',
'pointerdesign',
'for',
'maintainabilitydesign',
'patterndevelopment',
'helldevopsdiamond',
'of',
'deathdiaperdictionarydigitaldijkstras',
'algorithmdirected',
'acyclic',
'graphdirected',
'graphdirectivedistributed',
'data',
'protocol',
'(ddp)div',
'soupdivide',
'and',
'conquerdjangodnfdns',
'(domain',
'name',
'system)dockerdocusaurusdomain-specific',
'languagedongledosdowncastingdp',
'(data',
'processing)dp9ikdr',
'(disaster',
'recovery)drink',
'your',
'own',
'champagnedry',
'codedry',
'principle',
'(dont',
'repeat',
'yourself)dsl',
'(domain',
'specific',
'language)duck',
'punchingduck',
'typingduffs',
'devicedummydynamic',
'programmingdynamic',
'typingdynamicate'
];


// for ($i=0; $i < $argv[1]; $i++) { 
//     fwrite($file,$data[random_int(0,9)].PHP_EOL);
// }
while(true)
{
    $line = "";
    $file = fopen("input.txt","a");
    $line = $line . $data[random_int(0,9)];
    for ($i=0; $i < random_int(2,5); $i++) { 
        $line = $line . $words[random_int(0, count($words) -1)];
        $line = $line . " ";
    }
    $line = $line . PHP_EOL;
    fwrite($file, $line);
    fclose($file);
    echo $line;
    usleep(30000);

}